"""Writes public/js/core/config.js: the Shopify settings the browser may see.

Run: python3 scripts/build_config.py
(locally after editing .env; Cloudflare Pages runs it on every build)

Only PUBLIC_KEYS are written; server-only keys (the private token, the client
secret) never reach the site. With no store configured it writes
`shopify: null`, and the site runs on its own data.
"""

from __future__ import annotations

import json
import re

from environment import load_env
from paths import CONFIG_JS

# Environment variable -> config.js field.
PUBLIC_KEYS = {
    'SHOPIFY_STORE_DOMAIN': 'domain',
    'SHOPIFY_API_VERSION': 'apiVersion',
    'SHOPIFY_STOREFRONT_PUBLIC_TOKEN': 'publicToken',
}
DOMAIN_PATTERN = r'[a-z0-9][a-z0-9-]*\.myshopify\.com'
# Shopify releases an API version every quarter: 2026-01, -04, -07, -10.
VERSION_PATTERN = r'\d{4}-(01|04|07|10)'


def public_config(env: dict[str, str]) -> dict[str, str] | None:
    """Picks and checks the settings the site may expose.

    Args:
        env: Settings from load_env().

    Returns:
        The config.js fields, or None when no store is configured (an API
        version on its own, as in the .env template, doesn't count).

    Raises:
        SystemExit: Some but not all keys are set, or a value is malformed.
    """
    has_store = (
        'SHOPIFY_STORE_DOMAIN' in env
        or 'SHOPIFY_STOREFRONT_PUBLIC_TOKEN' in env
    )
    if not has_store:
        return None
    missing = [key for key in PUBLIC_KEYS if key not in env]
    if missing:
        raise SystemExit(
            f'config: set all of {", ".join(PUBLIC_KEYS)} or none '
            f'(missing {", ".join(missing)})'
        )
    shopify = {field: env[key] for key, field in PUBLIC_KEYS.items()}
    if not re.fullmatch(DOMAIN_PATTERN, shopify['domain']):
        raise SystemExit(
            "config: SHOPIFY_STORE_DOMAIN must be the store's .myshopify.com "
            'domain'
        )
    if not re.fullmatch(VERSION_PATTERN, shopify['apiVersion']):
        raise SystemExit('config: SHOPIFY_API_VERSION must look like 2026-10')
    return shopify


def config_js(shopify: dict[str, str] | None) -> str:
    """Returns the source of config.js.

    Args:
        shopify: The fields from public_config(), or None.
    """
    fields = json.dumps(shopify)
    return (
        '// Generated by scripts/build_config.py from the environment. '
        'Public values only; do not edit.\n'
        f'const radarConfig = Object.freeze({{shopify: {fields}}});\n'
    )


def main() -> None:
    """Writes config.js from the current settings."""
    shopify = public_config(load_env())
    CONFIG_JS.write_text(config_js(shopify))
    if shopify:
        store = f'Shopify {shopify["domain"]} (API {shopify["apiVersion"]})'
    else:
        store = 'no store configured'
    print(f'config.js: {store}')


if __name__ == '__main__':
    main()
