"""Makes Shopify the catalogue's source: reads the store into products.json.

Run:
  python3 scripts/sync_shopify.py                  write products.json from the
                                                   store
  python3 scripts/sync_shopify.py --check          compare the store with
                                                   products.json; writes
                                                   nothing (exit 1 if they
                                                   differ)
  python3 scripts/sync_shopify.py --if-configured  do nothing when the Admin
                                                   keys aren't set, so the
                                                   build uses the committed
                                                   products.json (Cloudflare
                                                   Pages builds use this)
  python3 scripts/sync_shopify.py --no-write-back  don't save assigned ids,
                                                   rings or bearings back to
                                                   Shopify
Then run build_data.py, which checks the result.

What counts (everything else in the store is ignored):
- collections with a radar.order metafield, in that order (at most
  RADAR_RINGS: the homepage locator draws four);
- ACTIVE products published to the Headless channel and in one of those
  collections.
A piece's position is its rank in its ring's manual order in Shopify. Fields
come from the radar.* metafields written by shopify_import.py; a product
created in the Shopify admin gets defaults (artwork title = product title...).
Pieces new to the radar get a site id, a ring and a free bearing, saved back
to Shopify so they never move. The artwork is the bundled public/assets file
named in radar.image when it exists, otherwise the product's featured image
on Shopify's CDN.
A store that can't be read, or data that fails a check, stops the build;
Cloudflare then keeps the last good deployment.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any, NamedTuple

from environment import load_env
from paths import ASSETS, PRODUCTS_JSON
from shopify_api import (
    Admin,
    Json,
    headless_publications,
    metafields,
    price_to_int,
)

RADAR_RINGS = 4
# metafieldsSet takes at most this many metafields at a time.
WRITE_BACK_BATCH = 25
SYNC_KEYS = (
    'SHOPIFY_STORE_DOMAIN',
    'SHOPIFY_CLIENT_ID',
    'SHOPIFY_CLIENT_SECRET',
)
ABOUT = (
    'Catalogue for the RADAR site. When the Shopify keys are set this file is '
    'generated by scripts/sync_shopify.py from the store (edit products in the '
    'Shopify admin); otherwise edit it here. Then run python3 '
    'scripts/build_data.py. Prices are in rupees; original > price marks a '
    'reduced piece. bearing is the permanent degree position on the collection '
    'ring; position is the curated order within the collection. media '
    '(optional) lists what the product page shows, in order: garment '
    'front/back, images and videos (paths relative to assets/). Without it a '
    'piece shows its garment front and back.'
)

COLLECTIONS = """query($after: String, $pub: ID!) {
  collections(first: 50, after: $after) {
    pageInfo { hasNextPage endCursor }
    nodes { id handle title description
      publishedOnPublication(publicationId: $pub)
      metafields(first: 10, namespace: "radar") { nodes { key value } } } } }"""
RING_ORDER = """query($id: ID!, $after: String) { collection(id: $id) {
  products(first: 250, after: $after, sortKey: COLLECTION_DEFAULT) {
    pageInfo { hasNextPage endCursor } nodes { id } } } }"""
PRODUCTS = """query($after: String, $pub: ID!) {
  products(first: 50, after: $after, query: "status:active") {
    pageInfo { hasNextPage endCursor }
    nodes { id title description productType tags
      publishedOnPublication(publicationId: $pub)
      featuredMedia { ... on MediaImage { image { url } } }
      variants(first: 20) { nodes { price compareAtPrice } }
      metafields(first: 30, namespace: "radar") { nodes { key value } } } } }"""
METAFIELDS_SET = """mutation($m: [MetafieldsSetInput!]!) {
  metafieldsSet(metafields: $m) {
    metafields { id } userErrors { field message } } }"""

Piece = dict[str, Any]
Collection = dict[str, Any]


class WriteBack(NamedTuple):
    """A radar.* metafield value to save back to a product."""

    owner: str  # the product's gid
    key: str
    type: str  # the metafield type, e.g. 'number_integer'
    value: str


class Ring(NamedTuple):
    """A radar collection: its radar.order, node and radar.* metafields."""

    order: int
    node: Json
    meta: dict[str, str]


def free_bearing(taken: list[int]) -> int:
    """Returns the middle of the widest gap between a ring's bearings.

    The same rule as freeBearing() in public/js/core/data.js, rounded to a
    whole degree that isn't taken.

    Args:
        taken: Bearings already used on the ring.
    """
    if not taken:
        return 0
    ordered = sorted(taken)
    widest, middle = 0, 0.0
    for index, bearing in enumerate(ordered):
        following = (
            ordered[index + 1] if index + 1 < len(ordered) else ordered[0] + 360
        )
        gap = following - bearing
        if gap > widest:
            widest, middle = gap, bearing + gap / 2
    result = round(middle) % 360
    # Rounding can land on a taken degree when the gaps are tiny.
    while result in taken:
        result = (result + 1) % 360
    return result


def headless_publication(admin: Admin) -> str:
    """Returns the first Headless channel publication's id.

    Args:
        admin: The session.

    Raises:
        SystemExit: The store has no Headless channel.
    """
    found = headless_publications(admin)
    if not found:
        raise SystemExit('sync: the store has no Headless channel')
    publication: str = found[0]['id']
    return publication


def radar_rings(admin: Admin, publication: str) -> list[Ring]:
    """Returns the collections on the radar, in radar.order.

    Args:
        admin: The session.
        publication: The Headless channel's id.

    Raises:
        SystemExit: There are none, or more than RADAR_RINGS.
    """
    rings = []
    for node in admin.pages(COLLECTIONS, ['collections'], {'pub': publication}):
        meta = metafields(node)
        if 'order' in meta and node['publishedOnPublication']:
            rings.append(Ring(int(meta['order']), node, meta))
    rings.sort(key=lambda ring: (ring.order, ring.node['title']))
    if not rings:
        raise SystemExit(
            'sync: no collection has radar.order and is on the Headless channel'
        )
    if len(rings) > RADAR_RINGS:
        raise SystemExit(
            f'sync: {len(rings)} radar collections; the homepage supports '
            f'{RADAR_RINGS}. Remove radar.order from the extra ones in the '
            'Shopify admin.'
        )
    return rings


def ring_orders(
    admin: Admin, rings: list[Ring]
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Reads each ring's manual product order.

    Args:
        admin: The session.
        rings: From radar_rings().

    Returns:
        (ring handle -> product gids in order, product gid -> the handles of
        the rings it is in).
    """
    order: dict[str, list[str]] = {}
    rings_of_product: dict[str, list[str]] = {}
    for ring in rings:
        handle = ring.node['handle']
        gids = [
            product['id']
            for product in admin.pages(
                RING_ORDER, ['collection', 'products'], {'id': ring.node['id']}
            )
        ]
        order[handle] = gids
        for gid in gids:
            rings_of_product.setdefault(gid, []).append(handle)
    return order, rings_of_product


class CatalogueReader:
    """Turns product nodes into pieces, assigning missing ids and rings."""

    def __init__(
        self,
        order: dict[str, list[str]],
        rings_of_product: dict[str, list[str]],
    ) -> None:
        """Prepares to read products in the given rings.

        Args:
            order: Ring handle -> product gids in order.
            rings_of_product: Product gid -> the handles of its rings.
        """
        self.order = order
        self.rings_of_product = rings_of_product
        self.write_backs: list[WriteBack] = []
        self.used_ids: set[str] = set()
        self.next_id = 1

    def reserve_ids(self, nodes: list[Json]) -> None:
        """Records the site ids already in use, so new ones don't clash.

        Args:
            nodes: Every product node being read.
        """
        self.used_ids = {
            field['value']
            for node in nodes
            for field in node['metafields']['nodes']
            if field['key'] == 'id'
        }
        numeric = [int(value) for value in self.used_ids if value.isdigit()]
        self.next_id = max(numeric, default=0) + 1

    def artwork(self, node: Json, meta: dict[str, str]) -> str | None:
        """Returns the bundled artwork file, else the featured image URL.

        Args:
            node: A product node.
            meta: Its radar.* metafields.
        """
        image = meta.get('image')
        if image and (ASSETS / image).is_file():
            return image
        url: str | None = (
            (node.get('featuredMedia') or {}).get('image') or {}
        ).get('url')
        return url

    def ring(self, node: Json, meta: dict[str, str]) -> str:
        """Returns the piece's ring, saving it back if it was missing or stale.

        A product in several radar collections keeps its radar.ring if that
        is one of them, otherwise takes the first.

        Args:
            node: A product node.
            meta: Its radar.* metafields.
        """
        rings = self.rings_of_product[node['id']]
        ring = meta['ring'] if meta.get('ring') in rings else rings[0]
        if meta.get('ring') != ring:
            self.write_backs.append(
                WriteBack(node['id'], 'ring', 'single_line_text_field', ring)
            )
        return ring

    def site_id(self, node: Json, meta: dict[str, str]) -> str:
        """Returns the piece's site id, assigning and saving a new one.

        Args:
            node: A product node.
            meta: Its radar.* metafields.
        """
        if meta.get('id'):
            return meta['id']
        while f'{self.next_id:02d}' in self.used_ids:
            self.next_id += 1
        new_id = f'{self.next_id:02d}'
        self.used_ids.add(new_id)
        self.write_backs.append(WriteBack(node['id'], 'id', 'id', new_id))
        return new_id

    def piece(self, node: Json) -> Piece | None:
        """Returns a node as a piece in the products.json shape.

        Args:
            node: A product node.

        Returns:
            The piece (its bearing None if it has none yet), or None if the
            product can't be shown (no artwork or no variants).
        """
        meta = metafields(node)
        image = self.artwork(node, meta)
        if not image:
            print(
                f'sync: skipping "{node["title"]}": no artwork image',
                file=sys.stderr,
            )
            return None
        variants = node['variants']['nodes']
        if not variants:
            print(
                f'sync: skipping "{node["title"]}": no variants',
                file=sys.stderr,
            )
            return None
        ring = self.ring(node, meta)
        piece_id = self.site_id(node, meta)
        prices = [price_to_int(variant['price']) for variant in variants]
        compare = [
            price_to_int(variant['compareAtPrice'])
            for variant in variants
            if variant['compareAtPrice']
        ]
        price = min(prices)
        tags = node['tags']
        # Key order is the order in products.json.
        piece: Piece = {
            'id': piece_id,
            'collection': ring,
            'position': self.order[ring].index(node['id']),
            'name': node['title'],
            'title': meta.get('artwork_title') or node['title'],
            'category': meta.get('category')
            or node['productType']
            or (tags[0] if tags else ''),
            'discipline': meta.get('discipline', ''),
            'year': meta.get('year', ''),
            'image': image,
            'price': price,
            'original': max([*compare, price]),
            'dark': meta.get('dark') == 'true',
            'bearing': int(meta['bearing']) if meta.get('bearing') else None,
            'description': node['description'],
            'status': meta.get('status', ''),
        }
        if meta.get('media'):
            piece['media'] = json.loads(meta['media'])
        return piece


def read_store(
    admin: Admin,
) -> tuple[list[Collection], list[Piece], list[WriteBack]]:
    """Reads the catalogue from the store.

    Args:
        admin: The session.

    Returns:
        (collections, pieces in ring then position order, values to save back
        to Shopify).

    Raises:
        SystemExit: The store's radar setup is invalid, or two pieces share a
            bearing on a ring.
    """
    publication = headless_publication(admin)
    rings = radar_rings(admin, publication)
    collections = [
        {
            'id': ring.node['handle'],
            'title': ring.node['title'],
            'copy': ring.meta.get('copy') or ring.node['description'],
        }
        for ring in rings
    ]
    order, rings_of_product = ring_orders(admin, rings)
    nodes = [
        node
        for node in admin.pages(PRODUCTS, ['products'], {'pub': publication})
        if node['publishedOnPublication'] and node['id'] in rings_of_product
    ]
    reader = CatalogueReader(order, rings_of_product)
    reader.reserve_ids(nodes)
    bearings: dict[str, list[int]] = {c['id']: [] for c in collections}
    products: list[tuple[str, Piece]] = []
    for node in nodes:
        piece = reader.piece(node)
        if piece is None:
            continue
        taken = bearings[piece['collection']]
        if piece['bearing'] is not None:
            if piece['bearing'] in taken:
                raise SystemExit(
                    f'sync: {piece["id"]} "{piece["name"]}" shares bearing '
                    f'{piece["bearing"]} on {piece["collection"]}; clear '
                    'radar.bearing on one of them and sync again to assign a '
                    'free one'
                )
            taken.append(piece['bearing'])
        products.append((node['id'], piece))
    # Second pass: pieces new to the radar take free bearings.
    for gid, piece in products:
        if piece['bearing'] is None:
            taken = bearings[piece['collection']]
            bearing = free_bearing(taken)
            piece['bearing'] = bearing
            taken.append(bearing)
            reader.write_backs.append(
                WriteBack(gid, 'bearing', 'number_integer', str(bearing))
            )
    pieces = [piece for _, piece in products]
    rank_positions(pieces, list(order))
    ranked = [
        piece
        for collection in collections
        for piece in sorted(
            (p for p in pieces if p['collection'] == collection['id']),
            key=lambda p: p['position'],
        )
    ]
    return collections, ranked, reader.write_backs


def rank_positions(pieces: list[Piece], rings: list[str]) -> None:
    """Renumbers positions as ranks among the pieces kept on each ring.

    Args:
        pieces: Changed in place.
        rings: Ring handles.
    """
    for ring in rings:
        kept = sorted(
            (piece for piece in pieces if piece['collection'] == ring),
            key=lambda piece: piece['position'],
        )
        for rank, piece in enumerate(kept):
            piece['position'] = rank


def save_write_backs(admin: Admin, write_backs: list[WriteBack]) -> None:
    """Saves assigned ids, rings and bearings to the products' metafields.

    Args:
        admin: The session.
        write_backs: What to save.
    """
    for start in range(0, len(write_backs), WRITE_BACK_BATCH):
        batch = write_backs[start : start + WRITE_BACK_BATCH]
        admin.graphql(
            METAFIELDS_SET,
            {
                'm': [
                    {
                        'ownerId': item.owner,
                        'namespace': 'radar',
                        'key': item.key,
                        'type': item.type,
                        'value': item.value,
                    }
                    for item in batch
                ]
            },
        )
    for item in write_backs:
        product = item.owner.rsplit('/', 1)[-1]
        print(f'  saved radar.{item.key} = {item.value} on {product}')


def print_differences(
    current: Json, collections: list[Collection], products: list[Piece]
) -> None:
    """Lists which pieces differ between products.json and the store.

    Args:
        current: products.json as it is.
        collections: From the store.
        products: From the store.
    """
    before = {piece['id']: piece for piece in current['products']}
    after = {piece['id']: piece for piece in products}
    for piece_id in sorted(set(before) | set(after)):
        old, new = before.get(piece_id), after.get(piece_id)
        if old == new:
            continue
        if old is None:
            change = 'new in Shopify'
        elif new is None:
            change = 'gone from Shopify'
        else:
            change = ', '.join(
                sorted(
                    key
                    for key in set(old) | set(new)
                    if old.get(key) != new.get(key)
                )
            )
        print(f'  {piece_id}: {change}')
    if current['collections'] != collections:
        print('  collections differ')


def parse_args() -> argparse.Namespace:
    """Reads the command-line options."""
    parser = argparse.ArgumentParser(
        description='Read the catalogue from Shopify into products.json.'
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='compare the store with products.json; write nothing',
    )
    parser.add_argument(
        '--if-configured',
        action='store_true',
        help='do nothing when the Shopify Admin keys are not set',
    )
    parser.add_argument(
        '--no-write-back',
        action='store_true',
        help="don't save assigned ids, rings or bearings to Shopify",
    )
    return parser.parse_args()


def main() -> None:
    """Syncs (or, with --check, compares) the catalogue."""
    args = parse_args()
    env = load_env()
    if args.if_configured and not all(key in env for key in SYNC_KEYS):
        print(
            'sync: no Shopify Admin keys; using the committed '
            'public/data/products.json'
        )
        return
    admin = Admin(env)
    collections, products, write_backs = read_store(admin)
    current = json.loads(PRODUCTS_JSON.read_text())
    same = (
        current['collections'] == collections
        and current['products'] == products
    )
    print(
        f'sync: {admin.domain}: {len(products)} pieces in {len(collections)} '
        f'collections; {"matches" if same else "differs from"} products.json'
    )
    if args.check:
        if not same:
            print_differences(current, collections, products)
        sys.exit(0 if same else 1)
    if write_backs and not args.no_write_back:
        save_write_backs(admin, write_backs)
    catalogue = {
        '_about': ABOUT,
        'collections': collections,
        'products': products,
    }
    PRODUCTS_JSON.write_text(json.dumps(catalogue, indent=1) + '\n')


if __name__ == '__main__':
    main()
