"""Write site/scripts/config.js: the Shopify settings the browser is allowed to see.

Run: python3 tools/build_config.py   (locally after editing .env; Cloudflare Pages runs it on every build)

Reads the environment, and on a local machine also the repo's .env file (real environment variables win).
Only PUBLIC_KEYS are written; server-only keys (private token, client secret) never reach the site.
With no store configured it writes `shopify: null`, and the site runs on its own data, exactly as before.
Other tools import load_env() from here.
"""
from pathlib import Path
import json
import os
import re

repo = Path(__file__).resolve().parent.parent
PUBLIC_KEYS = {  # environment name -> config.js field
    'SHOPIFY_STORE_DOMAIN': 'domain',
    'SHOPIFY_API_VERSION': 'apiVersion',
    'SHOPIFY_STOREFRONT_PUBLIC_TOKEN': 'publicToken',
}


def load_env(path=repo / '.env'):
    """Return .env values overlaid with the real environment. Lines are KEY=value; # starts a comment."""
    values = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                values[key.strip()] = value.strip().strip('"\'')
    values.update({k: v for k, v in os.environ.items() if k.startswith('SHOPIFY_')})
    return {k: v for k, v in values.items() if v}


def public_config(env):
    if 'SHOPIFY_STORE_DOMAIN' not in env and 'SHOPIFY_STOREFRONT_PUBLIC_TOKEN' not in env:
        return None  # no store yet (the template's default API version alone doesn't count)
    shopify = {field: env[key] for key, field in PUBLIC_KEYS.items() if key in env}
    missing = [key for key in PUBLIC_KEYS if key not in env]
    if missing:
        raise SystemExit('config: set all of ' + ', '.join(PUBLIC_KEYS) + ' or none (missing ' + ', '.join(missing) + ')')
    if not re.fullmatch(r'[a-z0-9][a-z0-9-]*\.myshopify\.com', shopify['domain']):
        raise SystemExit('config: SHOPIFY_STORE_DOMAIN must be the store\'s .myshopify.com domain')
    if not re.fullmatch(r'\d{4}-(01|04|07|10)', shopify['apiVersion']):
        raise SystemExit('config: SHOPIFY_API_VERSION must look like 2026-10')
    return shopify


if __name__ == '__main__':
    shopify = public_config(load_env())
    target = repo / 'site' / 'scripts' / 'config.js'
    target.write_text('// Generated by tools/build_config.py from the environment. Public values only; do not edit.\n'
                      'const radarConfig = Object.freeze({shopify: ' + json.dumps(shopify) + '});\n')
    print(f'config.js: {"Shopify " + shopify["domain"] + " (API " + shopify["apiVersion"] + ")" if shopify else "no store configured"}')
