"""Make Shopify the catalogue's source: read the store and write site/data/products.json, then run build_data.py.

Run:
  python3 tools/sync_shopify.py                  write products.json from the store
  python3 tools/sync_shopify.py --check          compare the store with products.json; writes nothing (exit 1 if different)
  python3 tools/sync_shopify.py --if-configured  do nothing (exit 0) when the Admin keys aren't set: the build then uses
                                                 the committed products.json. Cloudflare Pages builds use this.
  python3 tools/sync_shopify.py --no-write-back  don't save assigned ids, rings or bearings back to Shopify

What counts (everything else in the store is ignored):
  - collections with a radar.order metafield, in that order (at most RADAR_RINGS: the homepage locator draws four)
  - ACTIVE products published to the Headless channel and in one of those collections
Position is a piece's rank in its ring's manual order in Shopify. Fields come from the radar.* metafields written by
shopify_import.py; a piece created in the Shopify admin gets defaults (artwork title = product title, etc.).
Pieces new to the radar get a site id, a ring and a free bearing, saved back to Shopify so they never move.
The artwork is the bundled site/assets file named in radar.image when it exists, otherwise the product's featured
image on Shopify's CDN (resized by URL in shared.js).
A store that can't be read, or data that fails a check, stops the build: Cloudflare keeps the last good deployment.
"""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parent.parent / 'site'
SOURCE = ROOT / 'data' / 'products.json'
RADAR_RINGS = 4
ABOUT = ('Catalogue for the RADAR site. When the Shopify keys are set this file is generated by tools/sync_shopify.py '
         'from the store (edit products in the Shopify admin); otherwise edit it here. Then run python3 tools/build_data.py. '
         'Prices are in rupees; original > price marks a reduced piece. bearing is the permanent degree position on the '
         'collection ring; position is the curated order within the collection. media (optional) lists what the product '
         'page shows, in order: garment front/back, images and videos (paths relative to assets/). Without it a piece '
         'shows its garment front and back.')

COLLECTIONS = '''query($after: String, $pub: ID!) { collections(first: 50, after: $after) {
  pageInfo { hasNextPage endCursor }
  nodes { id handle title description publishedOnPublication(publicationId: $pub)
    metafields(first: 10, namespace: "radar") { nodes { key value } } } } }'''
RING_ORDER = '''query($id: ID!, $after: String) { collection(id: $id) {
  products(first: 250, after: $after, sortKey: COLLECTION_DEFAULT) { pageInfo { hasNextPage endCursor } nodes { id } } } }'''
PRODUCTS = '''query($after: String, $pub: ID!) { products(first: 50, after: $after, query: "status:active") {
  pageInfo { hasNextPage endCursor }
  nodes { id title description productType tags publishedOnPublication(publicationId: $pub)
    featuredMedia { ... on MediaImage { image { url } } }
    variants(first: 20) { nodes { price compareAtPrice } }
    metafields(first: 30, namespace: "radar") { nodes { key value } } } } }'''


def free_bearing(taken):
    """The middle of the widest gap between bearings on a ring (same rule as freeBearing() in shared.js), rounded."""
    if not taken:
        return 0
    ordered = sorted(taken)
    widest, at = 0, 0
    for i, b in enumerate(ordered):
        gap = (ordered[i + 1] if i + 1 < len(ordered) else ordered[0] + 360) - b
        if gap > widest:
            widest, at = gap, b + gap / 2
    bearing = round(at) % 360
    while bearing in taken:  # rounding can land on a taken degree when gaps are tiny
        bearing = (bearing + 1) % 360
    return bearing


def money(value):
    return int(round(float(value)))


def read_store(admin):
    """Return (collections, products, write_backs) in the products.json shape."""
    publication = next(p['id'] for p in admin.graphql('{ publications(first: 50) { nodes { id name } } }')['publications']['nodes']
                       if 'headless' in p['name'].lower())
    rings = []
    for node in admin.pages(COLLECTIONS, ['collections'], {'pub': publication}):
        meta = {m['key']: m['value'] for m in node['metafields']['nodes']}
        if 'order' in meta and node['publishedOnPublication']:
            rings.append((int(meta['order']), node, meta))
    rings.sort(key=lambda r: (r[0], r[1]['title']))
    if not rings:
        raise SystemExit('sync: no collection has radar.order and is on the Headless channel')
    if len(rings) > RADAR_RINGS:
        raise SystemExit(f'sync: {len(rings)} radar collections; the homepage supports {RADAR_RINGS}. '
                         'Remove radar.order from the extra ones in the Shopify admin.')
    collections = [{'id': n['handle'], 'title': n['title'], 'copy': meta.get('copy') or n['description']} for _, n, meta in rings]
    ring_of_gid = {}
    order = {}
    for _, node, _ in rings:
        ids = [p['id'] for p in admin.pages(RING_ORDER, ['collection', 'products'], {'id': node['id']})]
        order[node['handle']] = ids
        for gid in ids:
            ring_of_gid.setdefault(gid, []).append(node['handle'])

    nodes = [n for n in admin.pages(PRODUCTS, ['products'], {'pub': publication})
             if n['publishedOnPublication'] and n['id'] in ring_of_gid]
    used_ids = {m['value'] for n in nodes for m in n['metafields']['nodes'] if m['key'] == 'id'}
    next_id = max((int(i) for i in used_ids if i.isdigit()), default=0) + 1
    products, write_backs, bearings = [], [], {c['id']: [] for c in collections}
    for node in nodes:  # first pass: fields and stored bearings
        meta = {m['key']: m['value'] for m in node['metafields']['nodes']}
        image = meta.get('image') if meta.get('image') and (ROOT / 'assets' / meta['image']).is_file() else None
        if not image:
            image = ((node.get('featuredMedia') or {}).get('image') or {}).get('url')
        if not image:
            print(f'sync: skipping "{node["title"]}": no artwork image', file=sys.stderr)
            continue
        if not node['variants']['nodes']:
            print(f'sync: skipping "{node["title"]}": no variants', file=sys.stderr)
            continue
        ring = meta['ring'] if meta.get('ring') in ring_of_gid[node['id']] else ring_of_gid[node['id']][0]
        if meta.get('ring') != ring:
            write_backs.append((node['id'], 'ring', 'single_line_text_field', ring))
        if not meta.get('id'):
            while f'{next_id:02d}' in used_ids:
                next_id += 1
            meta['id'] = f'{next_id:02d}'
            used_ids.add(meta['id'])
            write_backs.append((node['id'], 'id', 'id', meta['id']))
        prices = [money(v['price']) for v in node['variants']['nodes']]
        compare = [money(v['compareAtPrice']) for v in node['variants']['nodes'] if v['compareAtPrice']]
        price = min(prices)
        piece = {
            'id': meta['id'], 'collection': ring, 'position': order[ring].index(node['id']),
            'name': node['title'], 'title': meta.get('artwork_title') or node['title'],
            'category': meta.get('category') or node['productType'] or (node['tags'][0] if node['tags'] else ''),
            'discipline': meta.get('discipline', ''), 'year': meta.get('year', ''), 'image': image,
            'price': price, 'original': max(compare + [price]), 'dark': meta.get('dark') == 'true',
            'bearing': int(meta['bearing']) if meta.get('bearing') else None,
            'description': node['description'], 'status': meta.get('status', ''),
        }
        if meta.get('media'):
            piece['media'] = json.loads(meta['media'])
        if piece['bearing'] is not None:
            if piece['bearing'] in bearings[ring]:
                raise SystemExit(f'sync: {piece["id"]} "{piece["name"]}" shares bearing {piece["bearing"]} on {ring}; '
                                 'clear radar.bearing on one of them and sync again to assign a free one')
            bearings[ring].append(piece['bearing'])
        products.append((node['id'], piece))
    for gid, piece in products:  # second pass: new pieces take free bearings
        if piece['bearing'] is None:
            piece['bearing'] = free_bearing(bearings[piece['collection']])
            bearings[piece['collection']].append(piece['bearing'])
            write_backs.append((gid, 'bearing', 'number_integer', str(piece['bearing'])))
    for ring in order:  # positions are ranks among the pieces kept on that ring
        kept = sorted((p for _, p in products if p['collection'] == ring), key=lambda p: p['position'])
        for rank, p in enumerate(kept):
            p['position'] = rank
    ranked = [p for c in collections for p in sorted((p for _, p in products if p['collection'] == c['id']), key=lambda p: p['position'])]
    return collections, ranked, write_backs


def save_write_backs(admin, write_backs):
    for start in range(0, len(write_backs), 25):  # metafieldsSet takes up to 25 at a time
        batch = write_backs[start:start + 25]
        admin.graphql('''mutation($m: [MetafieldsSetInput!]!) { metafieldsSet(metafields: $m) { metafields { id } userErrors { field message } } }''',
                      {'m': [{'ownerId': gid, 'namespace': 'radar', 'key': key, 'type': kind, 'value': value} for gid, key, kind, value in batch]})
    for gid, key, _, value in write_backs:
        print(f'  saved radar.{key} = {value} on {gid.rsplit("/", 1)[-1]}')


def main():
    args = sys.argv[1:]
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from build_config import load_env
    env = load_env()
    if '--if-configured' in args and not all(k in env for k in ('SHOPIFY_STORE_DOMAIN', 'SHOPIFY_CLIENT_ID', 'SHOPIFY_CLIENT_SECRET')):
        print('sync: no Shopify Admin keys; using the committed site/data/products.json')
        return
    from shopify_api import Admin
    admin = Admin(env)
    collections, products, write_backs = read_store(admin)
    current = json.loads(SOURCE.read_text())
    same = current['collections'] == collections and current['products'] == products
    print(f'sync: {admin.domain}: {len(products)} pieces in {len(collections)} collections; '
          f'{"matches" if same else "differs from"} products.json')
    if '--check' in args:
        if not same:
            before = {p['id']: p for p in current['products']}
            after = {p['id']: p for p in products}
            for i in sorted(set(before) | set(after)):
                if before.get(i) != after.get(i):
                    keys = sorted(k for k in set(before.get(i, {})) | set(after.get(i, {}))
                                  if (before.get(i) or {}).get(k) != (after.get(i) or {}).get(k))
                    print(f'  {i}: ' + ('new in Shopify' if i not in before else 'gone from Shopify' if i not in after else ', '.join(keys)))
            if current['collections'] != collections:
                print('  collections differ')
        sys.exit(0 if same else 1)
    if write_backs and '--no-write-back' not in args:
        save_write_backs(admin, write_backs)
    SOURCE.write_text(json.dumps({'_about': ABOUT, 'collections': collections, 'products': products}, indent=1) + '\n')


if __name__ == '__main__':
    main()
